### PR TITLE
fix: createComponent() should accept tuple props

### PR DESCRIPTION
**Pull request by wjw99830**
[#146](https://github.com/vuejs/composition-api/issues/146#issue-499062781)
Current `createComponent()` couldn't accept tuple props because of a type-error.
Now this works:
```typescript
createComponent({
  props: ['p1', 'p2'] as const,
  setup(props) {
    props.p1 // any
  },
});
```

### CODE REVIEW

**Comment by pikax** [comment]
why is `const` needed?

**Comment by wjw99830** [comment]
@pikax
```typescript
type PropKeys<O extends readonly string[]> = O[number];
```
If we don't use `const`, generic type O will be `string` instead of union type.

**Comment by pikax** [comment]
in vue 2.x you can specify with an array without `as const` I think it should be the same here.

**Comment by wjw99830** [comment]
But current `createComponent()` reports an type-error when accept array props and `const` is not required if we don't need type inference or pass a generic argument for props.

**Comment by antfu** [comment]
Close in favor of #364. Thanks for your contribution.

**Pull request closed without merging**
