### PR TITLE
docs: improve translation

### PR DESCRIPTION
**Pull request by kidonng**
~~Close #74~~

Improve translation.

### CODE REVIEW

**Comment by kidonng** [comment]
@liximomo Should we translate "unwrap" to "自动展开" like in https://zhuanlan.zhihu.com/p/68477600?

**Comment by posva** [comment]
Hey, this is not nice, you are dismissing @zhuyst work by submitting a PR that closes theirs. It would be okay if it was an old PR where the author was not updating the PR but it was literally opened 3 hours ago. Can you instead propose the changes on the other PR, please?

**Comment by kidonng** [comment]
Sorry, I was initially intended to [point out a typo](https://github.com/vuejs/vue-function-api/pull/74#discussion_r317094107) but found more, so I revised the full README and this PR included #74's changes.
I'm not dismissing @zhuyst's work, this is only a workflow, just like in https://github.com/sindresorhus/refined-github/pull/2359 I closed https://github.com/sindresorhus/refined-github/pull/2358. Still, my bad for not crediting them.

**Comment by posva** [comment]
Thank you for that 🙂! it's great you are contributing but,

> I'm not dismissing @zhuyst's work, this is only a workflow

Unfortunately, yes, you are. By saying _Close #74_, you are **literally** dismissing the original PR 😔. It's not about workflows. Some people may not care like it happened in that PR for refined-github but others will not appreciate at all or even worse, be hurt and not dare to say anything... There is no rush in merging that PR, leaving suggestion and wait is more effective and respectful 🙌

Don't get me wrong, I appreciate the initiative to contribute! It was the context and the way it was executed that I didn't appreciate.

**Comment by kidonng** [comment]
> There is no rush in merging that PR, leaving suggestion and wait is more effective and respectful

Absolutely! I should have behaved more respectful and not to duplicate other's work. I'm really sorry for my carelessness.

Now that #74 has been merged, could you please kindly reopen this (or should I create another one instead)?

**Comment by posva** [comment]
No worries! I reopened it, you might want to rebase against master if you didn't

**Comment by leopiccionia** [comment]
@kidonng I've added a PR with additional typo fixes to your fork.

**Comment by kidonng** [comment]
@liximomo Could you please take a look at the changes and see if it looks good to you?

**Comment by liximomo** [comment]
@kidonng Please open separate PRs which focus only one thing at a time.

**Comment by kidonng** [comment]
@liximomo Fine, this PR will focus on improving the translation.

**Comment by kidonng** [comment]
@liximomo How do you like it now?

**Comment by liximomo** [comment]
@kidonng Please open a new PR based on the latest master branch, It's difficult to review this one.

**Pull request closed without merging**
