### PR TITLE
Support reactive object with 'value' property

### LINKED ISSUE #157: Type infer error if interface has "value" property
define an interface A:
```javasciprt
interface A {
	id:string
	...
	value:string
}
```
if using with **toRefs**
```javascript
toRefs(reactive({a:<A[]>[]}))
```
as an export use function:
```javascript
function useValue(){
	return toRefs(reactive({a:<A[]>[]}))
}
const { a } = useValue()
```

here, type infer is error, **a is to be Ref<string[]>, not be Ref<A[]>**
if A has no property value, it works ok.

### LINKED ISSUE #159: Return type for reactive was wrong
like this:
WX20191018-142502@2x

### PR DESCRIPTION
**Pull request by dvic**
- fixes #157
- fixes #159

### CODE REVIEW

**Comment by dvic** [comment]
@liximomo thoughts?

**Comment by renyamizuno** [comment]
So cool! 🆒 

but this pattern fail. (may be)

image

**Comment by dvic** [comment]
@renyamizuno interesting, maybe this could be solved using the new recursive types support in TS, but I'll have to check.

**Comment by LinusBorg** [comment]
I think this will be solved more elegantly with #199 

If you agree I'll close his.

**Comment by dvic** [comment]
agreed, this can be closed

**Pull request closed without merging**
