### PR TITLE
perf: more light-weight computed

### PR DESCRIPTION
**Pull request by shaonialife**

### CODE REVIEW

**Comment by antfu** [comment]
Interesting, can you have a simple pref compare on this? Thanks

**Comment by shaonialife** [comment]
相对于原来的实现, 现在的 computed 只用到一个 Watcher 对象, 而原来的用到了 Vue对象, 在初始化 Vue 实例时, 需要做很多额外的工作, 比如调用生命周期方法等, 相比较而言, 只用 Watcher 对象要轻量得多, 我在项目中已经这样用了一个月多了, 没有发现什么奇怪的问题

**Comment by antfu** [comment]
@shaonialife This PR looks promising and I would love to have this improvement, but before getting this merged, we should have a pref test/benchmarking to show the difference. I can do that when I got some time. Or if you would like to try, please feel free to do so. Thanks!

**Comment by shaonialife** [comment]
@antfu 仅仅是一个内存占用测试, 没有测试其他项目 https://github.com/shaonialife/vue-computed-mem-test

**Comment by antfu** [comment]
@shaonialife Wow, that's a huge improvement, thanks for your work :) 

The code looks good to me, /cc @pikax what do you think?

**Pull request merged**
