### PR TITLE
feat: add isVNode api

### PR DESCRIPTION
**Pull request by shaonialife**

### CODE REVIEW

**Comment by shaonialife** [comment]
emm... yarn install err...😳, who can help me

**Comment by pikax** [comment]
looks like npm and yarn are having issues

**Comment by shaonialife** [comment]
ok fine, I will try later

**Comment by pikax** [comment]
Thank you for this, but `isVNode` is not part of the composition-api.

https://github.com/vuejs/composition-api/pull/438#issuecomment-658263664

**Comment by shaonialife** [comment]
Well, I just see```isVNode``` in the miss API on readME

**Pull request closed without merging**
